# config.py

import os

# --- Directory Settings ---
# The main directory where all user-uploaded and indexed files are stored.
CACHE_DIR = "IDXDB"

# A dedicated directory for storing files generated by the "Mixup" feature.
# This helps keep the main directory clean.
GENERATED_FILES_DIR = "generated"


# --- File Settings ---
# The name of the CSV file that stores the search index created by FiberDBMS.
# This file is crucial for the chatbot and search functionalities.
INDEX_FILE = "arcana_index.csv"


# --- Application Settings ---
# The title of the Streamlit application.
APP_TITLE = "Arcana"

# A list of supported file extensions that the application can process and index.
SUPPORTED_FILE_TYPES = ["txt", "pdf", "csv", "docx", "pptx"]

# For long response (Qwen model)
QWEN_API_KEY = ""  # Enter your Qwen API key here
QWEN_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1" 